### ISSUE TITLE
USER STORY (Backend): Account registration

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/organisation_app_api#1]
As a **visitor** I can **register for an account** so that **I can have a user profile with picture and have full access to the site, make, comment on and like posts and events**

Frontend issue: https://github.com/dragon-fire-fly/organisation_app_frontend/issues/1

#  Acceptance Criteria
- New users can create user accounts
- User accounts automatically have user profiles associated with them
- JWT Tokens add a layer of security during the log in process
- Logged in users have **permission** to create, edit and delete their own posts and events
- Logged in users have **permission** to comment and like other's posts and events

# Tasks
- [x] Create log in process 
- [x] Add and configure JWT tokens
- [x] Add permission classes for logged in users
