### ISSUE TITLE
USER STORY (Backend): Create and edit user profiles

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/organisation_app_api#10]
As a **user** I can **have a profile created for me, add a profile picture and edit my profile** so that **I can have a custom profile picture and display information about myself**

Frontend issue: https://github.com/dragon-fire-fly/organisation_app_frontend/issues/10

#  Acceptance Criteria
- A user profile is automatically created when a user account is created
- Users can view their own profile and have permission to edit it
- The new user profile is added to the list of user accounts
- Users can add a custom profile image

# Tasks
- [x] Add Profile model to DRF 
- [x] Auto-create profile on user creation
- [x] Picture field on profile allows picture upload
- [x] Default picture assigned to profile when users first sign up
