### ISSUE TITLE
USER STORY (Backend): Log in functionality

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/organisation_app_api#11]
As a **registered user** I can **log in to my account** so that **I can have full access to the site, make, comment on and like posts and events**

Frontend issue: https://github.com/dragon-fire-fly/organisation_app_frontend/issues/11

#  Acceptance Criteria
- Registered users can sign in on the sign in page
- If user details are entered incorrectly, users receive appropriate error messages
- When users successfully log in, they are redirected to the main fed page

# Tasks

- [x] JWT token and refresh token issued
- [x] JWT token expiry extended
- [x] Add current user serializer so user is accessible everywhere
