### ISSUE TITLE
USER STORY (Backend): View user profiles

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/organisation_app_api#12]
As a **user** I can **view other user's profiles** so that I can **see a specific user's posts and events**

Frontend issue: https://github.com/dragon-fire-fly/organisation_app_frontend/issues/12

#  Acceptance Criteria
- Users can see other user's individual profile pages
- Profile pages show specific user's posts and events
- Profile pages show counts for comments, followers and events

# Tasks
- [x] View individual profile page route
- [x] Returns data on a specific user
- [x] Appropriate filters show post, follower and event counts
