### ISSUE TITLE
USER STORY (Backend): Create new event

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/organisation_app_api#13]
As a **user** I can **create events** so that **I can share information about events with other users**

Frontend issue: https://github.com/dragon-fire-fly/organisation_app_frontend/issues/13

#  Acceptance Criteria
- Users can create new events
- Submitting the new event form creates a event entry in the db
- Only logged in users can create posts

# Tasks
- [x] Create Event model in DRF
- [x] Add “create new event” endpoint
- [x] Add associated serializer & view
