### ISSUE TITLE
USER STORY (Backend): Edit and delete events

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/organisation_app_api#14]
As a **user** I can **edit or delete my own events** so that **I can fix incorrect information, add more information, or remove the event entirely**

Frontend issue: https://github.com/dragon-fire-fly/organisation_app_frontend/issues/14

#  Acceptance Criteria
- Users can edit and delete existing events
- Submitting the edit event form edits a specific event entry in the db
- Deleting the event deletes a specific event entry and all associated memories from the db
- Only the event owner has permission to edit or delete a event

# Tasks
- [x] Add endpoints for editing and deleting events
- [x] Add associated serializer & view
- [x] Add permission class for logged in users
