### ISSUE TITLE
USER STORY (Backend): Like and unlike posts

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/organisation_app_api#15]
As a **user** I can **like other user's posts** so that **I can show that user I appreciated their content**

Frontend issue: https://github.com/dragon-fire-fly/organisation_app_frontend/issues/15

#  Acceptance Criteria
- Logged in users can like posts
- Liked posts gain an increase in likes by 1
- Clicking "like" again will remove the like and associated counts
- Logged out users and post owners cannot like a post

# Tasks
- [x] Create Like model in DRF
- [x] Add like and like detail endpoints
- [x] Add associated serializers and views
