### ISSUE TITLE
USER STORY (Backend): Add comments to posts

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/organisation_app_api#16]
As a **user** I can **create comments on posts** so that **I can communicate with the poster and other users about the post content**

Frontend issue: https://github.com/dragon-fire-fly/organisation_app_frontend/issues/16

#  Acceptance Criteria
- Logged in users can add comments to posts
- A comment form is rendered on the individual post page
- The comment count for posts with comments increases by one for each comment
- Logged out users cannot leave comments

# Tasks
- [x] Create comment model in DRF
- [x] Add comment and comment detail endpoints
- [x] Add associated serializers and views
- [x] Add filters for comments to posts
