### ISSUE TITLE
USER STORY (Backend): Watch and unwatch events

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/organisation_app_api#18]
As a **user** I can **watch/unwatch other user's posts** so that **it is added to my watched events list**

Frontend issue: https://github.com/dragon-fire-fly/organisation_app_frontend/issues/18

#  Acceptance Criteria
- Logged in users can click "watch" events which adds them to their watch list
- Watched events gain an increase in watchers by 1
- Clicking "watch" again will remove the watch and associated counts
- Logged out users and post owners cannot watch an event

# Tasks
- [x] Create Watch model in DRF
- [x] Add watch and watch detail endpoints
- [x] Add associated serializers and views
