### ISSUE TITLE
USER STORY (Backend): View posts as a visitor

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/organisation_app_api#2]
As a **visitor** I can **view a list of posts** so that **I can view recent uploads and decide if I want to sign up**

Frontend issue: https://github.com/dragon-fire-fly/organisation_app_frontend/issues/2

#  Acceptance Criteria
- The list view API endpoints can be viewed by users who are not logged in
- Appropriate permissions allow visitors to view but not create, edit or delete posts
- Clicking an event takes the visitor to the individual post page

# Tasks
- [x] Create the list view for posts
- [x] Apply appropriate permissions for visitors vs logged in users
- [x] Add appropriate API endpoint URI
