### ISSUE TITLE
USER STORY (Backend): Calendar assignment on registration

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/organisation_app_api#20]
As a **user** I am **automatically assigned a calendar** so that **I can easily view my events**

Frontend issue: https://github.com/dragon-fire-fly/organisation_app_frontend/issues/20

#  Acceptance Criteria
- Calendar automatically generated and linked to user
- Calendar button in navbar takes user to calendar page
- Calendar page renders user's calendar

# Tasks
- [x] Add calendar model (linked to user)
- [x] Add associated serializers and views
- [x] Add urls for calendars and individual calendar
