### ISSUE TITLE
USER STORY (Backend): Add an event to a post

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/organisation_app_api#29]
As a **user** I can **choose an event from my event list when I post** so that **I can make a post about that specific event**

Frontend issue: https://github.com/dragon-fire-fly/organisation_app_frontend/issues/29

#  Acceptance Criteria
- A drop down menu allows users to optionally select an event to add to their post
- A user can select any event from their event list (their own events or ones they've added to calendar)
- In API post has a field called "event" and events have a field called "posts" which are both updated on a new post with associated event

# Tasks
- [x] Add event foreign key (one to many relationship) to post model
- [x] Add posts field to event serializer
- [x] Add serialized event to post
