### ISSUE TITLE
USER STORY (Backend): View events as a visitor

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/organisation_app_api#3]
As a **visitor** I can **view public events** so that **I can see what events are planned and see if I would like to create an account to add the event(s) to my calendar**

Frontend issue: https://github.com/dragon-fire-fly/organisation_app_frontend/issues/3

#  Acceptance Criteria
- The list view API endpoints can be viewed by users who are not logged in
- Appropriate permissions allow visitors to view but not create, edit or delete events
- Clicking an event takes the visitor to the individual event page

# Tasks
- [x] Create the list view for events
- [x] Apply appropriate permissions for visitors vs logged in users
- [x] Add appropriate API endpoint URI
