### ISSUE TITLE
USER STORY (Backend): Add and remove friends from friends list

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/organisation_app_api#35]
As a **user** I can **add other users as friends** so that **I can preferentially see their posts and events**

Frontend issue: https://github.com/dragon-fire-fly/organisation_app_frontend/issues/35

#  Acceptance Criteria
- Users can add other users as friends
- Adding a friend increases the user's "friends" count and the other user's "added by" count by 1
- Once a friend is added, users have the option to remove the friend, reducing the counts by 1

# Tasks
- [x] Add follower app with owner and followed as foreign keys in follower model
- [x] Add associated serializers, urls and views
- [x] Add appropriate filters and unique together for owner and followed
