### ISSUE TITLE
USER STORY (Backend): View individual posts as a visitor

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/organisation_app_api#4]
As a **visitor** I can **view individual posts** so that **I can read the post in more detail and see the associated comments**

Frontend issue: https://github.com/dragon-fire-fly/organisation_app_frontend/issues/4

#  Acceptance Criteria
- The detail view API endpoints can be viewed by users who are not logged in
- Appropriate permissions allow visitors to view but not create, edit or delete posts
- Individual posts have their associated comments visible to visitors

# Tasks
- [x] Create the detail view for posts
- [x] Apply appropriate permissions for visitors vs logged in users
- [x] Add appropriate API endpoint URI
