### ISSUE TITLE
USER STORY (Backend): Memories

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/organisation_app_api#40]
As a **user** I can **add memories to past events** so that **I can store my comments and images to look at later**

Frontend issue: https://github.com/dragon-fire-fly/organisation_app_frontend/issues/40

#  Acceptance Criteria
- Users can add "memories" to events
- Memories are displayed on the event's detail page
- Memories may only be added by logged in users

# Tasks
- [x] Add memories app
- [x] Associate memories with events through foreign keys
- [x] Create associated serializers, urls and views
