### ISSUE TITLE
USER STORY (Backend): Edit and delete memories

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/organisation_app_api#41]
As a **user** I can **edit or delete my own memories** so that **I can fix incorrect information, add more information, or remove the memory entirely**

Frontend issue: https://github.com/dragon-fire-fly/organisation_app_frontend/issues/41

#  Acceptance Criteria
- User who owns the memory can click “edit memory” button
- An “edit memory” form is rendered on the event page
- A specified memory is deleted when the user clicks the “delete memory” button
- Only the memory owner has permission to edit or delete a memory

# Tasks
- [x] Add edit and delete memory API endpoints
- [x] Add associated serializers and views for editing and deleting memories
- [x] Add permissions so that only memory owners can edit or delete memories
- [x] Add filter backends for memories to events
