### ISSUE TITLE
USER STORY (Backend): Link to Google calendar

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/organisation_app_api#45]
As a **user** I can **link my google account to my EventTrove account** so that **events I add in one place will be shown in the other **

Frontend issue: https://github.com/dragon-fire-fly/organisation_app_frontend/issues/45

#  Acceptance Criteria
- Users can log in using their Google credentials
- A new calendar is created in Google calendars upon account creation
- events can be synchronized across platforms

# Tasks
- [ ] Link to Google calendar API
- [ ] Insert a new calendar into Google calendar upon account creation
- [ ] Retrieve events from Google calendar and add to event list for that user
- [ ] Add events created in EventTrove to the Google calendar
