### ISSUE TITLE
USER STORY (Backend): View individual events as a visitor

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/organisation_app_api#5]
As a **visitor** I can **view individual events** so that **I can see more detail about the event and see any associated comments**

Frontend issue: https://github.com/dragon-fire-fly/organisation_app_frontend/issues/5

#  Acceptance Criteria
- The detail view API endpoints can be viewed by users who are not logged in
- Appropriate permissions allow visitors to view but not create, edit or delete events
- Individual events have their associated comments visible to visitors

# Tasks
- [x] Create the detail view for events
- [x] Apply appropriate permissions for visitors vs logged in users
- [x] Add appropriate API endpoint URI
