### ISSUE TITLE
USER STORY (Backend): Create new post

### ISSUE THREAD

**Issue by dragon-fire-fly** [dragon-fire-fly/organisation_app_api#8]
As a **user** I can **create posts** so that **I can share information about events with other users**

https://github.com/dragon-fire-fly/organisation_app_frontend/issues/8

#  Acceptance Criteria
- Users can create new posts
- Submitting the new post form creates a post entry in the db

# Tasks
- [x] Creat Post model in DRF 
- [x] Add “create new post” endpoint
- [x] Add associated serializer & view
